# Generated by Django 3.1.5 on 2021-01-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Division Code')),
                ('division_name', models.CharField(max_length=20, verbose_name='Division Name')),
            ],
            options={
                'db_table': 'division',
            },
        ),
    ]
