# Generated by Django 3.1.5 on 2021-01-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='District Code')),
                ('district_name', models.CharField(max_length=20, verbose_name='Ditrict Nmae')),
            ],
            options={
                'db_table': 'district',
            },
        ),
    ]
