# Generated by Django 3.1.5 on 2021-01-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0002_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('thana_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Thana Code')),
                ('thana_name', models.CharField(max_length=20, verbose_name='Thana Name')),
            ],
            options={
                'db_table': 'thana',
            },
        ),
    ]
