# Generated by Django 3.1.5 on 2021-02-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0003_thana'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPoint',
            fields=[
                ('market_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Market Point Code')),
                ('market_name', models.CharField(max_length=20, verbose_name='Market Point Name')),
            ],
            options={
                'db_table': 'market',
            },
        ),
    ]
