# Generated by Django 3.1.6 on 2021-02-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0004_marketpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Zone Code')),
                ('zone_name', models.CharField(max_length=20, verbose_name='Zone Name')),
            ],
            options={
                'db_table': 'zone',
            },
        ),
    ]
