# Generated by Django 3.1.7 on 2021-03-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0005_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='District Code'),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Division Code'),
        ),
        migrations.AlterField(
            model_name='marketpoint',
            name='market_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Market Point Code'),
        ),
        migrations.AlterField(
            model_name='thana',
            name='thana_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Thana Code'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Zone Code'),
        ),
    ]
