# Generated by Django 3.1.7 on 2021-04-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0007_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
