# Generated by Django 3.1.7 on 2021-04-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpbdapp", "0007_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="block_no",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Block No"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_no1",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Contact No 1"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_no2",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Contact No 2"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_no3",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Contact No 3"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="entry_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Entry By"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="front_length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Front Length"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="front_width",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Front Width"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gps_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="GPS Lattitude",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gps_long",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="GPS Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="holding_no",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Holding No"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="manager_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Manager/Incharge Name",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nid",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="NID/Trade License No",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="outlet_landmark",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Outlet Landmark"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="outlet_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Outlet Name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="outlet_type",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Outlet Type"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="owner_name",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="Owner Name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="post_office",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Post Office"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="respondent_designation",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Respondent Designation",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="road_name",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Road Name/No"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="storage_capacity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Storage Capacity"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="survey_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Survey By"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="total_staff",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Staff"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="union",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Union"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="village",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Village/Ward"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="visit_date",
            field=models.DateField(blank=True, null=True, verbose_name="Visit Date"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="weekly_holiday",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Weekly Holiday"
            ),
        ),
    ]
