# Generated by Django 3.1.7 on 2021-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0007_auto_20210512_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_staff',
        ),
        migrations.AddField(
            model_name='profile',
            name='business_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Business Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gerographical_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geographical Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='outlet_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Outlet Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_established',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year of Estbalishment,'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='outlet_landmark',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Outlet Landmark'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='village',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Village/Ward'),
        ),
    ]
