# Generated by Django 3.1.7 on 2021-05-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0009_remove_profile_outlet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gps_lat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gps_long',
        ),
    ]
