# Generated by Django 3.1.7 on 2021-05-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0010_auto_20210518_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='storage_capacity',
        ),
    ]
