# Generated by Django 3.1.7 on 2021-05-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0011_remove_profile_storage_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weekly_holiday',
        ),
    ]
