# Generated by Django 3.1.7 on 2021-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0013_auto_20210518_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='road_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Road Name/No'),
        ),
    ]
