# Generated by Django 3.1.7 on 2021-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0014_auto_20210518_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='road_name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Road Name/No'),
        ),
    ]
