# Generated by Django 3.1.7 on 2021-05-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0015_auto_20210519_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='potential_as_crown_dealer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'Female')], max_length=50, null=True, verbose_name='Potential as Crown Dealer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='potential_as_crown_merchandising',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'Female')], max_length=50, null=True, verbose_name='Potential as Crown Dealer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='potential_as_crown_retailer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'Female')], max_length=50, null=True, verbose_name='Potential as Crown Dealer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='under_crown_dealer',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Under Crown Dealer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='under_crown_sr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Under Crown SR'),
        ),
    ]
