# Generated by Django 3.1.7 on 2021-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0016_auto_20210527_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='potential_as_crown_dealer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Potential as Crown Dealer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='potential_as_crown_merchandising',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Potential as Crown Dealer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='potential_as_crown_retailer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Potential as Crown Dealer'),
        ),
    ]
