# Generated by Django 3.1.7 on 2021-05-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0017_auto_20210527_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Visit Month')),
                ('merchandising_tools', models.CharField(blank=True, max_length=200, null=True, verbose_name='Merchandising tools')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('brand_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.brand')),
                ('outlet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.profile')),
            ],
            options={
                'db_table': 'merchandising',
            },
        ),
    ]
