# Generated by Django 3.1.7 on 2021-06-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0018_merchandising'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.CharField(blank=True, max_length=30, null=True, verbose_name='Start Month')),
                ('end_month', models.CharField(blank=True, max_length=30, null=True, verbose_name='End Month')),
                ('visit_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Visit Year')),
                ('vb', models.CharField(blank=True, max_length=15, null=True, verbose_name='Visible Brand')),
                ('start_month_volume', models.SmallIntegerField(blank=True, null=True, verbose_name='Start Month Volume')),
                ('end_month_volume', models.SmallIntegerField(blank=True, null=True, verbose_name='End Month Volume')),
                ('purchase_min', models.SmallIntegerField(blank=True, null=True, verbose_name='Purchase Min')),
                ('purchase_max', models.SmallIntegerField(blank=True, null=True, verbose_name='Purchase Max')),
                ('sales_min', models.SmallIntegerField(blank=True, null=True, verbose_name='Sales Min')),
                ('sales_max', models.SmallIntegerField(blank=True, null=True, verbose_name='Sales Max')),
                ('purchase_source', models.CharField(blank=True, max_length=20, null=True, verbose_name='Purchase Source')),
                ('satisfaction_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Satisfaction Level')),
                ('do_to_delivery', models.SmallIntegerField(blank=True, null=True, verbose_name='Do to Delivery(in hrs)')),
                ('monthly_credit', models.SmallIntegerField(blank=True, null=True, verbose_name='Monthly Credit')),
                ('brand_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.brand')),
                ('outlet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.profile')),
            ],
            options={
                'db_table': 'retail',
            },
        ),
    ]
