# Generated by Django 3.1.7 on 2021-09-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0020_profile_division_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail',
            name='end_month',
            field=models.DateField(blank=True, null=True, verbose_name='End Month'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='start_month',
            field=models.DateField(blank=True, null=True, verbose_name='Start Month'),
        ),
    ]
