# Generated by Django 3.1.7 on 2021-09-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0021_auto_20210914_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='outlet_type_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Outlet Type ID'),
        ),
    ]
