# Generated by Django 3.1.7 on 2021-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0022_auto_20210920_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='holding_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Holding No'),
        ),
    ]
