# Generated by Django 3.1.7 on 2021-10-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0023_auto_20210927_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('dealer_id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Dealer ID')),
                ('dealer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dealer Name')),
                ('holding_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Holding No')),
                ('road_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Road Name/No')),
                ('block_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Block No')),
                ('union', models.CharField(blank=True, max_length=255, null=True, verbose_name='Union')),
                ('post_office', models.CharField(blank=True, max_length=255, null=True, verbose_name='Post Office')),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Name')),
                ('respondent_designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Respondent Designation')),
                ('contact_no1', models.CharField(blank=True, max_length=11, null=True, verbose_name='Contact No.1')),
                ('contact_no2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Contact No.3')),
                ('total_staff', models.IntegerField(blank=True, null=True, verbose_name='Total Staff No.')),
                ('outlet_landmark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outlet Landmark')),
                ('outlet_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outlet Status')),
                ('year_of_establishment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Year of Establishment')),
                ('monthly_average_volume', models.IntegerField(blank=True, null=True, verbose_name='Monthly avg. total volume')),
                ('total_retail', models.IntegerField(blank=True, null=True, verbose_name='Total Retail')),
                ('self_transport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Self-Transport')),
                ('storage_capacity', models.BigIntegerField(blank=True, null=True, verbose_name='Storage Capacity')),
                ('front_length', models.IntegerField(blank=True, null=True, verbose_name='Front Length(ft)')),
                ('front_width', models.IntegerField(blank=True, null=True, verbose_name='Front Width(ft)')),
                ('business_pattern', models.CharField(blank=True, max_length=255, null=True, verbose_name='Busiense Pattern with %')),
                ('nid', models.CharField(blank=True, max_length=255, null=True, verbose_name='NID/TRADE License no.')),
                ('asset', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asset')),
                ('liability', models.CharField(blank=True, max_length=255, null=True, verbose_name='Liability')),
                ('business_ethics', models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Ethics')),
                ('successor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Successor')),
                ('under_crowns_dealer', models.CharField(blank=True, max_length=255, null=True, verbose_name="Under Crown's Dealer")),
                ('under_crowns_sr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Under Crowns SR')),
                ('potential_crown_dealer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Potential as Crown Dealer')),
                ('potential_crown_retailer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Potential as Crown Retailer')),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.district')),
                ('division_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.division')),
                ('market_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.marketpoint')),
                ('thana_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.thana')),
                ('zone_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.zone')),
            ],
            options={
                'db_table': 'dealer_profile',
            },
        ),
    ]
