# Generated by Django 3.1.7 on 2021-10-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0024_dealerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerShipBrand',
            fields=[
                ('dealership_code', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='Dealership Code')),
                ('delivery_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Source')),
                ('brand_wise_manpower', models.IntegerField(blank=True, null=True, verbose_name='Brand Wise Manpower')),
                ('brand_wise_retail', models.IntegerField(blank=True, null=True, verbose_name='Brand Wise Retail')),
                ('brand_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.brand')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.dealerprofile')),
                ('distribution_area_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.marketpoint')),
                ('distribution_area_thana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.thana')),
            ],
            options={
                'db_table': 'dealership_brand',
            },
        ),
    ]
