# Generated by Django 3.1.7 on 2021-10-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0025_dealershipbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerShipSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start Month')),
                ('end_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='End Month')),
                ('start_month_sales_volume', models.IntegerField(blank=True, null=True, verbose_name='Start Month Sales Volume')),
                ('end_month_sales_volume', models.IntegerField(blank=True, null=True, verbose_name='End Month Sales Volume')),
                ('landing_pricce', models.IntegerField(blank=True, null=True, verbose_name='Landing Price')),
                ('dp', models.IntegerField(blank=True, null=True, verbose_name='DP')),
                ('tp', models.IntegerField(blank=True, null=True, verbose_name='TP')),
                ('eup', models.IntegerField(blank=True, null=True, verbose_name='EUP')),
                ('do_to_delivery_time', models.IntegerField(blank=True, null=True, verbose_name='Do to delivery time')),
                ('monthly_credit', models.IntegerField(blank=True, null=True, verbose_name='Monthly Credit')),
                ('micro_delivery', models.IntegerField(blank=True, null=True, verbose_name='Micro Delivery in bags')),
                ('dealership_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpbdapp.dealershipbrand')),
            ],
            options={
                'db_table': 'dealership_sales',
            },
        ),
    ]
