# Generated by Django 3.1.7 on 2021-10-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpbdapp', '0026_dealershipsales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Status'),
        ),
    ]
